import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'
import { Card, Text } from './components/Card'

const mudar = (arrActive, setArrActive) => {
  const primeitoItem = arrActive[0];
  const novoArr = arrActive;
  novoArr.shift();
  novoArr.push(primeitoItem);
  setArrActive(novoArr);
  console.log('🟢', arrActive);
  alert(`[ ${arrActive[0]}, ${arrActive[1]}, ${arrActive[2]}, ${arrActive[3]} ]`)
}



export default function Home() {
  const [arrActive, setArrActive] = useState([false, false, true, false]);
  
  useEffect(() => mudar(arrActive, setArrActive), []);

  return (
    <div className={styles.container} onClick={() => mudar(arrActive, setArrActive)}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{'Titulo'}</h1>
        <h1 className={styles.title}>
          {`[ ${arrActive[0]}, ${arrActive[1]}, ${arrActive[2]}, ${arrActive[3]} ]`}
        </h1>

        <div className={styles.grid}>
          {
            arrActive.map((item, id) => (
              <Card active={item} key={id}>
                <Text>{`Texto ${item}`}</Text>
              </Card>
            ))
          }

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
